sudo: false
language: php
php:
  - 5.6
  - 7.0
env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.3.4
script:
  - curl -sSL https://raw.githubusercontent.com/hws47a/MageTestStand/master/setup.sh | bash
after_script:
  - rm composer.json
